services:
  app:
    build: .
    container_name: my-app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"  # Usa la variabile PORT dal file .env
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mydb
      - DB_PASSWORD=passw  # Usa la variabile dal file .env
      - DB_USER=root
    depends_on:
      - db



  db:
    image: mysql:latest
    container_name: my-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=passw  # Usa la variabile dal file .env
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
